image: node:latest

pages:
  only:
    #- tags
    - mains

  script:
    - yarn build@vercel

  artifacts:
    #enabled: false
    paths:
      - public
  #expire_in: 20 minutes

  cache:
    paths:
      - node_modules

#https://semantic-release.gitbook.io/semantic-release/v/beta/recipes/recipes/gitlab-ci
# The release pipeline will run only if all jobs in the test pipeline are successful
stages:
    - test
    - release

before_script:
  - yarn install

publish:
  image: node:latest
  stage: release
  script:
    - npx semantic-release
