# https://www.kancloud.cn/kancloud/learn-vimscript-the-hard-way/49323
# https://learnvimscriptthehardway.stevelosh.com/
# https://vimjc.com/

# pkg: clang(pacman)
# time vim -u NONE -c exit
# spell_check: z= or C-x&s
# gf: go file
# file jump: C-i C-o
# split: `sg  `sv `st
# `, q r' == q
# whitespace:  spc t w

[options]
    enable_guicolors = true
    statusline_iseparator = "sharp"
    statusline_separator = "sharp"
    filetree_direction = "right"
    enable_vimfiler_welcome = 0
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true
    bootstrap_before = "myspacevim#before"
    bootstrap_after  = "myspacevim#after"
    guifont = "Droid Sans Mono:h11"
    statusline_unicode_symbols = true
    enable_os_fileformat_icon = true
    wrap_line=0
    default_indent = 2
    filemanager = "nerdtree"
    colorscheme_bg = "dark"
    colorscheme = "SpaceVim"
    autocomplete_method="coc"

[[layers]]
    name = 'autocomplete'
    auto_completion_tab_key_behavior = "smart"
    auto-completion-return-key-behavior = "smart"
    auto-completion-delay = 1

[[layers]]
    name = 'lang#sh'

# [[layers]]
  # name = 'lang#markdown'

# shortkeys: ctrl p and  spc f f (parent dir)
# multi cursor: spc s e
# spc f r : open recent files
# spc f f : search file
# ctrl+p
[[layers]]
    name = "leaderf"

[[layers]]
  name = 'ui'

[[layers]]
    name = 'shell'
    default_position = 'float'
    default_height = 80

[[layers]]
    name = "colorscheme"

[[layers]]
    name = "incsearch"

# spc w c
# mm mn mp ma mi mc
[[layers]]
  name = "tools"

[[layers]]
  name = "lang#toml"

[[layers]]
  name = "lang#vim"

[[layers]]
  name = "lang#python"

[[layers]]
  name = "lang#c"
    enable_clang_syntax_highlight = true
  [layer.clang_std]
    cpp = "c11"

[[layers]]
  name = "lsp"
  filetypes = [
        "c",
        "cpp"
    ]

[layers.override_cmd]
  c = ["clangd"]

[[layers]]
  name = "format"

[[custom_plugins]]
  repo = 'machakann/vim-highlightedyank'

[[custom_plugins]]
  repo = "airblade/vim-gitgutter"
  # hook_add = ''' '''

[[custom_plugins]]
  repo = "ryanoasis/vim-devicons"

[[custom_plugins]]
  repo = 'voldikss/vim-translator'

[[custom_plugins]]
  repo = 'yianwillis/vimcdoc'

[[custom_plugins]]
  repo = "ap/vim-css-color"

[[custom_plugins]]
  repo = "justinmk/vim-syntax-extra"

[[custom_plugins]]
  repo = "jszakmeister/vim-togglecursor"

[[custom_plugins]]
  repo = 'bronson/vim-trailing-whitespace'

# pkg: [sudo] npm -g install instant-markdown-d
# cd .cache/vimfiles/repos/github.com/instant-markdown/vim-instant-markdown/ && yarn install
# if it doesn't work, please use :SPReinstall
[[custom_plugins]]
repo = 'instant-markdown/vim-instant-markdown'
