# https://www.kancloud.cn/kancloud/learn-vimscript-the-hard-way/49323
# https://learnvimscriptthehardway.stevelosh.com/
# https://vimjc.com/

# vanilla: vim -u NONE
# split: st
# , q r == q

[options]
    enable_guicolors = true
    statusline_iseparator = "nil"  # for nerdtree like
    statusline_separator = "nil"  # for statusline
    enable_vimfiler_welcome = 0  # show nerdtree automatically in welcome
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true
    bootstrap_before = "myspacevim#before"
    bootstrap_after  = "myspacevim#after"
    guifont = "Droid Sans Mono:h11"
    statusline_unicode_symbols = true
    wrap_line=0  # enable wrapline: 1
    checkinstall = 1  # enable: 1, autoinstall plugin
    default_indent = 2
    filetree_direction = "right"
    filemanager = "nerdtree"  # if nil, disable filemanager
    colorscheme = "SpaceVim"

# spc f w
[[layers]]
  name = "sudo"

# <leader> y or p  from sys
[[layers]]
  name = "default"

[[layers]]
    name = 'autocomplete'
    auto_completion_tab_key_behavior = "cycle"
    auto-completion-return-key-behavior = "smart"
    auto-completion-delay = 50

[[layers]]
    name = 'lang#sh'
    ebable = true

# ctrl+p
[[layers]]
    name = "leaderf"

[[layers]]
  name = 'ui'
  enable_sidebar = true
  enable_scrollbar = true
  enable_indentline = true
  enable_cursorword = false
  indentline_char = '|'
  conceallevel = 0
  concealcursor = ''
  cursorword_delay = 100
  cursorword_exclude_filetype = ['markdown', 'toml', 'org']
  indentline_exclude_filetyps = []
  enable = true

[[layers]]
    name = 'shell'
    default_position = 'float'  # float feature just support nvim
    default_height = 80

[[layers]]
    name = "colorscheme"

[[layers]]
    name = "incsearch"

# reading mode: spc w c goyo.vim
# add bookmarks: mm
[[layers]]
  name = "tools"

[[layers]]
  name = "lang#toml"

[[layers]]
  name = "lang#vim"

# dependencies: clang
[[layers]]
  name = "lang#c"
  enable_clang_syntax_highlight = true
  [layer.clang_std]
    cpp = "c11"

# rename symbols: spc l e
[[layers]]
  name = "lsp"
  filetypes = [
    "c",
  ]
  [layers.override_cmd]
    c = ["clangd"]

[[layers]]
  name = "format"
  format_on_save = true

[[custom_plugins]]
  repo = "ryanoasis/vim-devicons"

# zh_cn vimhelp
[[custom_plugins]]
  repo = 'yianwillis/vimcdoc'

[[custom_plugins]]
  repo = "ap/vim-css-color"

[[custom_plugins]]
  repo = "justinmk/vim-syntax-extra"

#  <leader> + spc"
[[custom_plugins]]
  repo = 'bronson/vim-trailing-whitespace'

[[custom_plugins]]
  repo = 'luochen1990/rainbow'

# spc f m
[[custom_plugins]]
  repo = 'iamcco/markdown-preview.nvim' # need cd .cache/vimfiles/.cache/vimrc/.deni/app && yarn or rm -rf .cache/vimfiles/repo/github/iamcoo and reinstall this plugin

# Ctrl+L or use  :h capslock
[[custom_plugins]]
  repo = 'tpope/vim-capslock'

[[custom_plugins]]
  repo = "machakann/vim-highlightedyank"
