# vimscript tutorial: 
# https://www.kancloud.cn/kancloud/learn-vimscript-the-hard-way/49323
# 2021-08-09 09:47:11 

# Options
# All SpaceVim option below [option] section
[options]
# terminal ture color
enable_guicolors = true
# top statine
statusline_iseparator = "arrow"
# buttom statine
statusline_separator = "arrow"

# icon type
buffer_index_type = 4
enable_tabline_filetype_icon = true
enable_statusline_mode = true

# bootstrap function
bootstrap_before = "myspacevim#before"
bootstrap_after  = "myspacevim#after"

# option: vimfiler nerdtree defx
filemanager = "vimfiler"

# option: onedark gruvbox
colorscheme = "palenight"

# font
guifont = "Droid Sans Mono:h11"

# Layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

# shortkeys: ctrl p and  spc f f (parent dir)
# multi cursor: spc s e
[[layers]]
name = "leaderf"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 50

[[layers]]
name = "colorscheme"

[[layers]]
name = "incsearch"

# spc w c : read mode (only one)
[[layers]]
name = "tools"

[[layers]]
name = "lang#toml"

[[layers]]
name = "sudo"
enable =false

[[layers]]
name = "tmux"
enable =false

[[layers]]
name = "lang#vim"

[[layers]]
name = "lang#python"
enable = false

[[layers]]
name = "lang#c"
enable_clang_syntax_highlight = true

[[layers]]
name = "lsp"
filetypes = [
  "c",
# "cpp"
]
[layers.override_cmd]
c = ["clangd"]

[[layers]]
name = "format"

[[layers]]
name = "debug"
enable = false

# Plugins
[[custom_plugins]]
repo = 'machakann/vim-highlightedyank'
merged = true

[[custom_plugins]]
repo = 'jceb/vim-orgmode'
merged = true
