# vimscript tutorial: 
# https://www.kancloud.cn/kancloud/learn-vimscript-the-hard-way/49323
# https://learnvimscriptthehardway.stevelosh.com/
# https://vimjc.com/

# Check log: SPC h L 
# for neovim: python-neovim(pacman)

## Options

# All SpaceVim option below [option] section
[options]
# terminal ture color
enable_guicolors = true
# top statine
statusline_iseparator = "arrow"
# buttom statine
statusline_separator = "arrow"

## Icon type

buffer_index_type = 4
enable_tabline_filetype_icon = true
enable_statusline_mode = true

# bootstrap function
bootstrap_before = "myspacevim#before"
bootstrap_after  = "myspacevim#after"

# option: vimfiler nerdtree defx
filemanager = "nerdtree"

# option: onedark gruvbox nord palenight
colorscheme = "onedark"
# colorscheme_bg = "dark"

# font
guifont = "Droid Sans Mono:h11"

# Layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

# shortkeys: ctrl p and  spc f f (parent dir)
# multi cursor: spc s e
# spc f r : open recent files
# spc f f : search file
# ctrl+p
[[layers]]
name = "leaderf"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 50

[[layers]]
name = "colorscheme"

[[layers]]
name = "incsearch"

# spc w c : read mode (only one)
[[layers]]
name = "tools"

[[layers]]
name = "lang#toml"

[[layers]]
name = "sudo"
enable =false

[[layers]]
name = "tmux"
enable =false

[[layers]]
name = "lang#vim"

[[layers]]
name = "lang#python"
enable = false

[[layers]]
name = "lang#c"
enable_clang_syntax_highlight = true

[[layers]]
name = "lsp"
filetypes = [
  "c",
# "cpp"
]
[layers.override_cmd]
c = ["clangd"]

[[layers]]
name = "format"

[[layers]]
name = "debug"
enable = false

## Plugins
# when in vim and nvim convert, this plugins need 
# use this command `SPUdate

[[custom_plugins]]
repo = 'machakann/vim-highlightedyank'
# merged = true

[[custom_plugins]]
repo = 'jceb/vim-orgmode'
# merged = true


# [[custom_plugins]]
# repo = "dstein64/vim-startuptime.git"
# merged = true

# just for git files is effect
[[custom_plugins]]
repo = "airblade/vim-gitgutter"

# kitty syntax
[[custom_plugins]]
repo = "fladson/vim-kitty"

[[custom_plugins]]
repo = "ryanoasis/vim-devicons"

[[custom_plugins]]
repo = "dracula/vim"

# [[disable_plugins]]
