# All SpaceVim option below [option] section
[options]
# set spacevim theme. by default colorscheme layer is not loaded,
# if you want to use more colorscheme, please load the colorscheme
# layer
# Disable guicolors in basic mode, many terminal do not support 24bit
# true colors
enable_guicolors = true
# Disable statusline separator, if you want to use other value, please
# install nerd fonts
statusline_separator = "arrow"
statusline_iseparator = "arrow"
buffer_index_type = 4
enable_tabline_filetype_icon = true
enable_statusline_mode = true
# wrap_line = true

# enable_googlesuggest = true

bootstrap_before = "myspacevim#before"
bootstrap_after  = "myspacevim#after"

filemanager = "defx"
# - vimfiler （默认）
# - nerdtree
# - defx

colorscheme = "palenight"
# colorscheme = "gruvbox"
# colorscheme_bg = "dark"
# colorscheme = "onedark"
# random_theme = true
# frequency = "daily"

# guifont = "SourceCodePro Nerd Font Mono:h11"
guifont = "Droid Sans Mono:h11"

# automatic_update = true

# # layer
# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30
enable = true

# onedark
[[layers]]
name = "colorscheme"

[[layers]]
name = "incsearch"

# [[custom_plugins]]
# repo = "lilydjwg/colorizer"
# on_cmd = ["ColorHighlight", "ColorToggle"]
# merged = false

# [[custom_plugins]]
# repo = "https://gitlab.com/code-stats/code-stats-vim.git"
# merged = false
# [options]
# 请注意，该值为一个 List，每一个选项为插件的名称，而非 github 仓库地址。
# disabled_plugins = ["clighter", "clighter8"]

# [[custom_plugins]]
# repo = 'luochen1990/rainbow'

[[layers]]
name = "lang#toml"

[[layers]]
name = "sudo"
enable =false

[[layers]]
name = "tmux"
enable =false

[[layers]]
name = "lang#vim"

[[layers]]
name = "lang#python"

[[layers]]
name = "lang#c"
enable_clang_syntax_highlight = true

[[layers]]
name = "lsp"
filetypes = [
  "c",
  "cpp"
]
[layers.override_cmd]
c = ["clangd"]

[[layers]]
name = "format"

[[layers]]
name = "debug"

# [options]

[[custom_plugins]]
repo = 'machakann/vim-highlightedyank'

# [[custom_plugins]]
# repo = 'luochen1990/rainbow'

[[custom_plugins]]
repo = 'justinmk/vim-syntax-extra'
