# https://www.kancloud.cn/kancloud/learn-vimscript-the-hard-way/49323
# https://learnvimscriptthehardway.stevelosh.com/
# https://vimjc.com/

# vanilla: vim -u NONE
# spell_check: z=
# gf: go file
# file jump: C-i C-o
# split: `sg  `sv `st
# ', q r' == 'q'

[options]
    enable_guicolors = true
    statusline_iseparator = "nil"  # for nerdtree like
    statusline_separator = "nil"  # for statusline
    enable_vimfiler_welcome = 0  # show nerdtree automatically in welcome
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true
    bootstrap_before = "myspacevim#before"
    bootstrap_after  = "myspacevim#after"
    guifont = "Droid Sans Mono:h11"
    statusline_unicode_symbols = true
    wrap_line=0  # enable wrapline: 1
    checkinstall = 1  # enable: 1, autoinstall plugin
    default_indent = 2
    filetree_direction = "right"
    filemanager = "nerdtree"  # if nil, disable filemanager
    colorscheme = "SpaceVim"

[[layers]]
    name = 'autocomplete'
    auto_completion_tab_key_behavior = "smart"
    auto-completion-return-key-behavior = "smart"
    auto-completion-delay = 1

[[layers]]
    name = 'lang#sh'

# ctrl+p
[[layers]]
    name = "leaderf"

[[layers]]
  name = 'ui'

[[layers]]
    name = 'shell'
    default_position = 'float'  # float feature just support nvim
    default_height = 80

[[layers]]
    name = "colorscheme"

[[layers]]
    name = "incsearch"

# reading mode: spc w c
# ann bookmarks: mm
[[layers]]
  name = "tools"

[[layers]]
  name = "lang#toml"

[[layers]]
  name = "lang#vim"

# dependencies: clang(pacman)
[[layers]]
  name = "lang#c"
  enable_clang_syntax_highlight = true
  [layer.clang_std]
    cpp = "c11"

[[layers]]
  name = "lsp"
  filetypes = [
    "c",
  ]
  [layers.override_cmd]
    c = ["clangd"]

[[layers]]
  name = "format"

[[custom_plugins]]
  repo = "ryanoasis/vim-devicons"

# chinese vim doc
[[custom_plugins]]
  repo = 'yianwillis/vimcdoc'

[[custom_plugins]]
  repo = "ap/vim-css-color"

[[custom_plugins]]
  repo = "justinmk/vim-syntax-extra"

#  use <leader> + whitespace"
# highlight whitespace:  spc t w
[[custom_plugins]]
  repo = 'bronson/vim-trailing-whitespace'

[[custom_plugins]]
  repo = 'luochen1990/rainbow'

# spc f m
[[custom_plugins]]
  repo = 'iamcco/markdown-preview.nvim' # need cd .cache/vimfiles/.cache/vimrc/.deni/app && yarn or rm -rf .cache/vimfiles/repo/github/iamcoo and reinstall this plugin

# Ctrl+L (insert) to toggle capslock
# :h capslock
[[custom_plugins]]
  repo = 'tpope/vim-capslock'

[[custom_plugins]]
  repo = "machakann/vim-highlightedyank"
