# vimscript tutorial: 
# https://www.kancloud.cn/kancloud/learn-vimscript-the-hard-way/49323
# https://learnvimscriptthehardway.stevelosh.com/
# https://vimjc.com/

# pkg: need install clang for lsp
# time vim -u NONE -c exit
# time vim  -c exit(todo -c ?or file)
# Check log: SPC h L 
# for neovim: python-neovim(pacman)
# spell_check: z= or C-x&s
# gf: go file
# C-i C-o

# All SpaceVim option below [option] section
[options]
enable_guicolors = true
statusline_iseparator = "sharp"
statusline_separator = "sharp"
filetree_direction = "right"
enable_vimfiler_welcome = 0
wrap_line=0
buffer_index_type = 4
enable_tabline_filetype_icon = true
enable_statusline_mode = true
bootstrap_before = "myspacevim#before"
bootstrap_after  = "myspacevim#after"
guifont = "Droid Sans Mono:h11"

# option: vimfiler nerdtree defx
# enable_vimfiler_filetypeicon = true
filemanager = "nerdtree"

# onedark gruvbox nord palenight NeoSolarized
# colorscheme_bg = "dark"
colorscheme = "SpaceVim"

[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = "lang#go"

# shortkeys: ctrl p and  spc f f (parent dir)
# multi cursor: spc s e
# spc f r : open recent files
# spc f f : search file
# ctrl+p
[[layers]]
name = "leaderf"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 50

[[layers]]
name = "colorscheme"

[[layers]]
name = "incsearch"

# spc w c 
# mm mn mp ma mi mc
[[layers]]
name = "tools"

[[layers]]
name = "lang#toml"

[[layers]]
name = "lang#vim"

[[layers]]
name = "lang#python"

[[layers]]
name = "lang#c"
enable_clang_syntax_highlight = true

[[layers]]
name = "lsp"
filetypes = [
  "c",
  "cpp"
]
[layers.override_cmd]
c = ["clangd"]

[[layers]]
name = "format"

[[layers]]
name = "debug"

[[custom_plugins]]
repo = 'machakann/vim-highlightedyank'

[[custom_plugins]]
repo = 'jceb/vim-orgmode'

[[custom_plugins]]
repo = "airblade/vim-gitgutter"

# kitty syntax
[[custom_plugins]]
repo = "fladson/vim-kitty"

[[custom_plugins]]
repo = "ryanoasis/vim-devicons"

[[custom_plugins]]
repo = 'voldikss/vim-translator'

[[custom_plugins]]
repo = "vimwiki/vimwiki"

[[custom_plugins]]
repo = 'yianwillis/vimcdoc'

[[custom_plugins]]
repo = "ap/vim-css-color"

[[custom_plugins]]
repo = "jszakmeister/vim-togglecursor"

# [[custom_plugins]]
# repo = "https://hub.fastgit.org/codota/tabnine-vim"

[[custom_plugins]]
repo = "justinmk/vim-syntax-extra"
