[git]
    autoCommit = false
    autoPush = false
[data]
    email = "jyao4783@gmail.com"
    name = "oeyoews"
# [edit]
#     command = "nvim"
    # args = ["--wait"]
[merge]
    command = "nvim"
    args = ["-d", "{{ .Destination }}", "{{ .Source }}"]
