[options]
enable_vimfiler_welcome = 0  # show nerdtree automatically in welcome
enable_tabline_filetype_icon = true
enable_statusline_mode = true
bootstrap_before = "myspacevim#before"
bootstrap_after  = "myspacevim#after"
guifont = "Droid Sans Mono:h11"
statusline_unicode_symbols = true
wrap_line=0  # enable wrapline: 1
checkinstall = 1  # enable: 1, autoinstall plugin
default_indent = 2
filetree_direction = "left"
filemanager = "nerdtree"  # if nil, disable filemanager
colorscheme = "SpaceVim"
autocomplete_method = 'coc'  # need crear dir ~/.config/coc
enable_guicolors = true
project_rooter_automatically = 1  # jump rooter folder
update_retry_cnt = 1  # retry times for plugin install
enable_filetree_gitstatus = false
disabled_plugins = ["neomake"]
# spc f w
[[layers]]
name = "sudo"

[[layers]]
name = 'git'
git_plugin = 'git'

# ctrl+p
[[layers]]
name = "leaderf"

[[layers]]
name = 'ui'
enable_sidebar = true
enable_indentline = false # show in welcome
indentline_char = '|'
conceallevel = 2  # hiden some symbols like markdown level: 2

[[layers]]
name = 'shell'
default_position = 'float'  # float feature just support nvim

[[layers]]
name = "colorscheme"

[[layers]]
name = "incsearch"

[[layers]]
name = "tools"

[[layers]]
name = 'lang#toml'

[[layers]]
name = 'lang#vim'
